In [514]:
import pandas as pd

# read data
trainingSet = pd.read_csv('training.csv')
testingSet = pd.read_csv('testing.csv')


In [515]:
# training data
x_train = trainingSet.iloc[:, :-1]
y_train = trainingSet.iloc[:, -1]


In [516]:
# testing data
x_test = testingSet.iloc[:, :-1]
y_test = testingSet.iloc[:, -1]


In [517]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)


In [518]:
# view the first five samples
x_train[:5], y_train[:5]


(array([[ 0.50764689,  0.26082397,  0.71851375, -1.06490152, -0.96050015,
          0.5938403 ,  0.18022769,  0.63153525, -0.9981937 ,  0.98670018],
        [ 0.79711445,  1.80061325,  1.31905642, -1.26011122, -1.00492521,
         -0.59083354, -0.96779308, -1.65719196, -1.01401087,  2.17958275],
        [ 0.85973872, -0.00476808, -0.30571822,  0.19395767,  0.04350629,
         -1.46942264,  0.85511814,  0.30133533, -0.59410056,  0.38919339],
        [ 1.36939089,  1.60682775,  0.61670184, -0.83670626, -1.09732934,
          1.40669341,  2.07963876,  1.06035761, -0.77888598,  1.18512592],
        [-0.57607705, -0.14040743,  0.44385348, -0.37653049, -0.44961191,
          0.0609053 ,  0.31029916, -0.3265348 , -0.71180371, -0.02813269]]),
 0    1
 1    0
 2    1
 3    0
 4    1
 Name: class, dtype: int64)

In [519]:
# view the first five samples
x_test[:5], y_test[:5]


(array([[-0.10678062, -0.33325232,  0.02986056, -0.8924032 , -0.94983813,
          0.14870248,  0.43522716, -0.49181634,  0.46470936,  0.72556009],
        [ 2.04859496,  2.86669614,  1.33170387, -1.43098729, -1.38964626,
          1.2349529 ,  2.2407478 , -3.43303578, -0.07709535, -2.12178126],
        [-0.32362952, -0.06164417,  0.00477647, -0.67502288, -0.59266062,
          0.17852845, -0.58535221, -0.83376742, -1.06627566, -0.54672936],
        [-0.68765555, -0.48190269, -1.03695113,  0.74497894,  0.80495189,
          0.22117535,  0.08443719, -0.55918017, -0.25928159, -1.42366019],
        [-0.75871896, -0.8056027 , -1.61409604,  1.79727275,  1.77430678,
          0.46532083,  0.09575282,  0.27216062, -0.26938577, -1.11172009]]),
 0    0
 1    0
 2    1
 3    1
 4    1
 Name: class, dtype: int64)

In [520]:
# turn data into tensors
import torch

x_train = torch.from_numpy(x_train).type(torch.float)
y_train = torch.from_numpy(y_train.to_numpy()).type(torch.float)

x_test = torch.from_numpy(x_test).type(torch.float)
y_test = torch.from_numpy(y_test.to_numpy()).type(torch.float)


In [521]:
# view the first five samples
x_train[:5], y_train[:5]


(tensor([[ 0.5076,  0.2608,  0.7185, -1.0649, -0.9605,  0.5938,  0.1802,  0.6315,
          -0.9982,  0.9867],
         [ 0.7971,  1.8006,  1.3191, -1.2601, -1.0049, -0.5908, -0.9678, -1.6572,
          -1.0140,  2.1796],
         [ 0.8597, -0.0048, -0.3057,  0.1940,  0.0435, -1.4694,  0.8551,  0.3013,
          -0.5941,  0.3892],
         [ 1.3694,  1.6068,  0.6167, -0.8367, -1.0973,  1.4067,  2.0796,  1.0604,
          -0.7789,  1.1851],
         [-0.5761, -0.1404,  0.4439, -0.3765, -0.4496,  0.0609,  0.3103, -0.3265,
          -0.7118, -0.0281]]),
 tensor([1., 0., 1., 0., 1.]))

In [522]:
# view the first five samples
x_test[:5], y_test[:5]


(tensor([[-0.1068, -0.3333,  0.0299, -0.8924, -0.9498,  0.1487,  0.4352, -0.4918,
           0.4647,  0.7256],
         [ 2.0486,  2.8667,  1.3317, -1.4310, -1.3896,  1.2350,  2.2407, -3.4330,
          -0.0771, -2.1218],
         [-0.3236, -0.0616,  0.0048, -0.6750, -0.5927,  0.1785, -0.5854, -0.8338,
          -1.0663, -0.5467],
         [-0.6877, -0.4819, -1.0370,  0.7450,  0.8050,  0.2212,  0.0844, -0.5592,
          -0.2593, -1.4237],
         [-0.7587, -0.8056, -1.6141,  1.7973,  1.7743,  0.4653,  0.0958,  0.2722,
          -0.2694, -1.1117]]),
 tensor([0., 0., 1., 1., 1.]))

In [523]:
# Standard PyTorch imports
import torch
from torch import nn

# Make device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cpu'

In [524]:
# 1. construct a model class that subclasses nn.Module
class dataModel(nn.Module):
    def __init__(self):
        super().__init__()
        # 2.create 2 nn.Linear layers capable of handling X and y input and output shapes
        # takes in 2 features (X), produces 5 features
        self.layer_1 = nn.Linear(in_features=10, out_features=100)
        # takes in 5 features, produces 1 feature (y)
        self.layer_2 = nn.Linear(in_features=100, out_features=1)

    # 3. define a forward method containing the forward pass computation
    def forward(self, x):
        # return the output of layer_2, a single feature, the same shape as y
        # computation goes through layer_1 first then the output of layer_1 goes through layer_2
        return self.layer_2(self.layer_1(x))


# 4. create an instance of the model and send it to target device
model_0 = dataModel().to(device)
model_0


dataModel(
  (layer_1): Linear(in_features=10, out_features=100, bias=True)
  (layer_2): Linear(in_features=100, out_features=1, bias=True)
)

In [525]:
# make predictions with the model
untrained_preds = model_0(x_test.to(device))
print(
    f"length of predictions: {len(untrained_preds)}, Shape: {untrained_preds.shape}")
print(f"length of test samples: {len(y_test)}, Shape: {y_test.shape}")
print(f"\nfirst 10 predictions:\n{untrained_preds[:10]}")
print(f"\nfirst 10 test labels:\n{y_test[:10]}")


length of predictions: 4012, Shape: torch.Size([4012, 1])
length of test samples: 4012, Shape: torch.Size([4012])

first 10 predictions:
tensor([[-0.1707],
        [-0.8624],
        [-0.3283],
        [-0.2704],
        [-0.0677],
        [-0.4338],
        [-0.2910],
        [ 0.0758],
        [ 0.0241],
        [-0.2348]], grad_fn=<SliceBackward0>)

first 10 test labels:
tensor([0., 0., 1., 1., 1., 0., 0., 1., 1., 0.])


In [526]:
# create a loss function
# loss_fn = nn.BCELoss() # BCELoss = no sigmoid built-in
loss_fn = nn.BCEWithLogitsLoss()  # BCEWithLogitsLoss = sigmoid built-in

# Create an optimizer
optimizer = torch.optim.SGD(params=model_0.parameters(), lr=0.1)


In [527]:
# calculate accuracy (a classification metric)
def accuracy_fn(y_true, y_pred):
    # torch.eq() calculates where two tensors are equal
    correct = torch.eq(y_true, y_pred).sum().item()
    acc = (correct / len(y_pred)) * 100
    return acc


In [528]:
# View the frist 5 outputs of the forward pass on the test data
y_logits = model_0(x_test.to(device))[:5]
y_logits


tensor([[-0.1707],
        [-0.8624],
        [-0.3283],
        [-0.2704],
        [-0.0677]], grad_fn=<SliceBackward0>)

In [529]:
# use sigmoid on model logits
y_pred_probs = torch.sigmoid(y_logits)
y_pred_probs


tensor([[0.4574],
        [0.2968],
        [0.4187],
        [0.4328],
        [0.4831]], grad_fn=<SigmoidBackward0>)

In [530]:
# find the predicted labels (round the prediction probabilities)
y_preds = torch.round(y_pred_probs)

# In full
y_pred_labels = torch.round(torch.sigmoid(model_0(x_test.to(device))[:5]))

# Check for equality
print(torch.eq(y_preds.squeeze(), y_pred_labels.squeeze()))

# Get rid of extra dimension
y_preds.squeeze()


tensor([True, True, True, True, True])


tensor([0., 0., 0., 0., 0.], grad_fn=<SqueezeBackward0>)

In [531]:
y_test[:5]


tensor([0., 0., 1., 1., 1.])

In [532]:
torch.manual_seed(42)

# Set the number of epochs
epochs = 100

# Put data to target device
x_train, y_train = x_train.to(device), y_train.to(device)
x_test, y_test = x_test.to(device), y_test.to(device)

# Build training and evaluation loop
for epoch in range(epochs):
    # Training
    model_0.train()

    # 1. Forward pass (model outputs raw logits)
    # squeeze to remove extra `1` dimensions, this won't work unless model and data are on same device
    y_logits = model_0(x_train).squeeze()
    # turn logits -> pred probs -> pred labls
    y_pred = torch.round(torch.sigmoid(y_logits))

    # 2. Calculate loss/accuracy
    # loss = loss_fn(torch.sigmoid(y_logits), # Using nn.BCELoss you need torch.sigmoid()
    #                y_train)
    loss = loss_fn(y_logits,  # Using nn.BCEWithLogitsLoss works with raw logits
                   y_train)
    acc = accuracy_fn(y_true=y_train,
                      y_pred=y_pred)

    # 3. Optimizer zero grad
    optimizer.zero_grad()

    # 4. Loss backwards
    loss.backward()

    # 5. Optimizer step
    optimizer.step()

    # Testing
    model_0.eval()
    with torch.inference_mode():
        # 1. Forward pass
        test_logits = model_0(x_test).squeeze()
        test_pred = torch.round(torch.sigmoid(test_logits))
        # 2. Caculate loss/accuracy
        test_loss = loss_fn(test_logits,
                            y_test)
        test_acc = accuracy_fn(y_true=y_test,
                               y_pred=test_pred)

    # Print out what's happening every 10 epochs
    if epoch % 10 == 0:
        print(
            f"Epoch: {epoch} | Loss: {loss:.5f}, Accuracy: {acc:.2f}% | Test loss: {test_loss:.5f}, Test acc: {test_acc:.2f}%")


Epoch: 0 | Loss: 0.69338, Accuracy: 51.13% | Test loss: 0.65148, Test acc: 64.13%
Epoch: 10 | Loss: 0.54142, Accuracy: 75.79% | Test loss: 0.54007, Test acc: 75.85%
Epoch: 20 | Loss: 0.51460, Accuracy: 76.06% | Test loss: 0.51781, Test acc: 76.05%
Epoch: 30 | Loss: 0.50434, Accuracy: 76.62% | Test loss: 0.50914, Test acc: 76.45%
Epoch: 40 | Loss: 0.49914, Accuracy: 76.92% | Test loss: 0.50467, Test acc: 76.77%
Epoch: 50 | Loss: 0.49607, Accuracy: 77.07% | Test loss: 0.50194, Test acc: 76.92%
Epoch: 60 | Loss: 0.49408, Accuracy: 77.09% | Test loss: 0.50010, Test acc: 77.09%
Epoch: 70 | Loss: 0.49272, Accuracy: 77.15% | Test loss: 0.49877, Test acc: 77.17%
Epoch: 80 | Loss: 0.49174, Accuracy: 77.04% | Test loss: 0.49778, Test acc: 77.29%
Epoch: 90 | Loss: 0.49102, Accuracy: 77.07% | Test loss: 0.49701, Test acc: 77.24%
